FROM ubuntu:22.04

RUN apt update && apt install -y \
    g++ cmake make git \
    libssl-dev libsodium-dev \
    libjsoncpp-dev uuid-dev \
    zlib1g-dev libcurl4-openssl-dev \
    python3 python3-pip \
    slurmd slurm-client \
    && rm -rf /var/lib/apt/lists/*

# Install Drogon from source
RUN git clone --depth 1 https://github.com/drogonframework/drogon.git /tmp/drogon && \
    cd /tmp/drogon && git submodule update --init && \
    mkdir build && cd build && \
    cmake .. && make -j$(nproc) && make install && ldconfig && \
    rm -rf /tmp/drogon

WORKDIR /app
COPY src/ ./src/
COPY CMakeLists.txt .

RUN mkdir build && cd build && cmake .. && make

EXPOSE 9000
CMD ["./build/coare_v2"]
